name: Create Data Release

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          path: "accidents"
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
      - name: Use Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
            cd accidents/scripts
            npm install
            pip install sqlite-utils
      - name: Run Data Processing
        run: |
            cd accidents/scripts
            npm run start
      - name: Create artifacts
        uses: actions/upload-artifact@v4
        with:
          name: processed
          path: accidents/scripts/processed.db

